version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"