version: 2
registries:
  central:
    type: "maven-repository"
    url: "https://repo.maven.apache.org/maven2"
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - central
    schedule:
      interval: "monthly"
    target-branch: "dependabot-staging-main"
    open-pull-requests-limit: 10
    groups:
      maven-plugins:
        patterns:
          - org.apache.maven.plugins*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dependabot-staging-main"
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - central
    schedule:
      interval: "monthly"
    target-branch: "dependabot-staging-spring33x"
    open-pull-requests-limit: 10
    groups:
      maven-plugins:
        patterns:
          - org.apache.maven.plugins*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dependabot-staging-spring33x"