version: 2
registries:
  central:
    type: "maven-repository"
    url: "https://repo.maven.apache.org/maven2"
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - central
    schedule:
      interval: "weekly"
    target-branch: "dependabot-staging-main"
    open-pull-requests-limit: 10
    groups:
      maven-plugins:
        patterns:
          - org.apache.maven.plugins*
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependabot-staging-main"
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - central
    schedule:
      interval: "weekly"
    target-branch: "dependabot-staging-spring34x"
    open-pull-requests-limit: 10
    groups:
      maven-plugins:
        patterns:
          - org.apache.maven.plugins*
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependabot-staging-spring34x"