name: Continuous Delivery

on:
  push:
    branches:
      - main
      - initial-commit

permissions:
  contents: write

concurrency:
  group: continuous-delivery

jobs:
  build-and-run-tests-and-deploy:
    name: Build, Run Tests, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven
        run: mvn -T 4 clean deploy